name: CartoniaApp
options:
  bundleIdPrefix: com.macky
  deploymentTarget:
    iOS: "15.0"

targets:
  CartoniaApp:
    type: application
    platform: iOS
    sources:
      - CartoniaApp
    resources:
      - CartoniaApp/Assets.xcassets
      - CartoniaApp/LaunchScreen.storyboard
    info:
      path: CartoniaApp/Info.plist
      properties:
        CFBundleName: CartoniaApp
        CFBundleIdentifier: com.macky.CartoniaApp
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
    dependencies:
      - framework: UIKit

  CartoniaAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - CartoniaAppTests
    dependencies:
      - target: CartoniaApp

  CartoniaAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - CartoniaAppUITests
    dependencies:
      - target: CartoniaApp

schemes:
  CartoniaApp:
    build:
      targets:
        CartoniaApp: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: CartoniaAppTests
        - name: CartoniaAppUITests
